<div class="header header-mobi-ext">
    <div class="container">
        <div class="row">
            <div class="col-md-2 col-sm-2">
                <a class="logo" href="<?php echo $this->getUrl('') ?>">
                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
                    <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
                </a>
            </div>
            <div class="col-md-10 pull-right">

                <?php // In order for the language switcher to display next to logo on smaller viewports, it will be moved here.
                // See app.js for details ?>
                <div class="store-language-container"></div>

                <!-- Skip Links -->

                <div class="skip-links">
                    <!-- <a href="#header-nav" class="skip-link skip-nav">
                        <span class="icon"></span>
                        <span class="label"><?php echo $this->__('Menu'); ?></span>
                    </a>

                    <a href="#header-search" class="skip-link skip-search">
                        <span class="icon"></span>
                        <span class="label"><?php echo $this->__('Search'); ?></span>
                    </a> -->

                    <div class="account-cart-wrapper">
                        <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#header-account" class="skip-link skip-account">
                            <span class="icon"></span>
                            <span class="label"><?php echo $this->__('Account'); ?></span>
                        </a>

                        <!-- Cart -->

                        <div class="header-minicart">
                            <?php echo $this->getChildHtml('minicart_head'); ?>
                        </div>
                    </div>


                </div>

                <!-- Navigation -->

                <div id="header-nav" class="skip-content">
                    <?php echo $this->getChildHtml('topMenu') ?>
                </div>

                <!-- Search -->

                <div id="header-search" class="skip-content col-md-6">
                    <?php echo $this->getChildHtml('topSearch') ?>
                </div>

                <!-- Account -->
<!--
                <div id="header-account" class="skip-content">
                    <?php # echo $this->getChildHtml('topLinks') ?>
                </div>
-->
		<ul class="header-navigation">
		    <li class="current"><a href="#promo-block">Home</a></li>
		    <li><a href="#about">About</a></li>
		    <li><a href="#services">Services</a></li>
            <li><a href="#benefits">Benefits</a></li>
		    <li><a href="#team">Team</a></li>
		    <li><a href="#contact">Contact</a></li>
		</ul>
            </div>
        </div>
    </div>
</div>


<?php echo $this->getChildHtml('topContainer'); ?>
<div class="clearfix"></div>
