<?php
$_product = $this->getProduct();

?>
<div class="product-essential">
    <div class="product-img-box">
        <a href="<?php echo $_product->getProductUrl(); ?>">
            <img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(230, 230) ?>" alt="">
        </a>
    </div>
    <div class="product-shop">
        <h1 class="product-name">
            <?php echo $_product->getName() ?>
        </h1>

        <h2><?php echo $this->__('Quick Overview'); ?></h2>
        <div class="short-description">
            <?php echo $_product->getShortDescription() ?>
        </div>

        <div class="divider">
        </div>

        <div class="row">
            <div class="col-md-6"><?php echo $this->getPriceHtml($_product); ?></div>
            <div class="col-md-6">
                <?php if($_product->isSaleable()): ?>
                    <button class="button btn btn-primary" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product); ?>')"><?php echo $this->__('Buy') ?></button>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
